# -*- coding: utf-8 -*-
"""ASL-CNN4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGoc-TC-f7wuFdwG9eU5GIrBxIAD6Mfd
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torch.nn.functional as F
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader, random_split
import matplotlib.pyplot as plt
import kagglehub
import json
import os
from google.colab import files

# Specifying the device to GPU/CPU. Here, 'cuda' means using 'gpu' and 'cpu' means using cpu only
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# Download latest version
path = kagglehub.dataset_download("grassknoted/asl-alphabet")
train_path = path + "/asl_alphabet_train/asl_alphabet_train"

print("Path to dataset files:", train_path)

# 3. Transforms (Now in full RGB Color)
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)) # Updated for 3 channels
])

dataset = ImageFolder(root=train_path, transform=transform)

# Split into Train and Validation (Testing)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

# Save classes for the webcam inference script
classes = dataset.classes
with open("asl_classes.json", "w") as f:
    json.dump(classes, f)

batch_size = 128
train_loader = DataLoader(
    train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True
)

# Improved CNN Architecture
class ImprovedCNN(nn.Module):
    def __init__(self, num_classes):
        super(ImprovedCNN, self).__init__()
        # Block 1 (Input is now 3 channels for RGB)
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)

        # Block 2
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)

        # Block 3
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)

        # Block 4 (NEW: Shrinks the spatial size down further)
        self.conv4 = nn.Conv2d(128, 256, kernel_size=3, padding=1)
        self.bn4 = nn.BatchNorm2d(256)

        self.pool = nn.MaxPool2d(2, 2)
        self.dropout = nn.Dropout(0.4)

        # Math: 128x128 passed through FOUR 2x2 pools becomes an 8x8 grid
        self.fc1 = nn.Linear(256 * 8 * 8, 512)
        self.fc2 = nn.Linear(512, num_classes)

    def forward(self, x):
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = self.pool(F.relu(self.bn3(self.conv3(x))))
        x = self.pool(F.relu(self.bn4(self.conv4(x)))) # Passing through 4th block

        x = x.view(x.size(0), -1)

        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)
        return x

num_classes = len(classes)
model = ImprovedCNN(num_classes).to(device)

criterion = nn.CrossEntropyLoss()
# Lowered learning rate for stability
optimizer = optim.Adam(model.parameters(), lr=0.001)

print(model)

# Tracking lists for graphs
train_accuracies, val_accuracies = [], []
train_losses, val_losses = [], []
epochs = 10

print("Starting Training...")
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    correct_train, total_train = 0, 0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()

    train_acc = 100 * correct_train / total_train
    train_loss = running_loss / len(train_loader)
    train_accuracies.append(train_acc)
    train_losses.append(train_loss)

    # Validation Phase
    model.eval()
    val_loss = 0.0
    correct_val, total_val = 0, 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            val_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            total_val += labels.size(0)
            correct_val += (predicted == labels).sum().item()

    val_acc = 100 * correct_val / total_val
    v_loss = val_loss / len(test_loader)
    val_accuracies.append(val_acc)
    val_losses.append(v_loss)

    print(f"Epoch [{epoch+1}/{epochs}] - "
          f"Train Loss: {train_loss:.4f}, Train Acc: {train_acc:.2f}% | "
          f"Val Loss: {v_loss:.4f}, Val Acc: {val_acc:.2f}%")

# 6. Save and Download Files
torch.save(model.state_dict(), 'asl_cnn_model.pth')
print("Downloading files to your local computer...")
files.download('asl_cnn_model.pth')
files.download('asl_classes.json')

# Plotting Accuracy and Loss Graphs
plt.figure(figsize=(12, 5))

# Accuracy Subplot
plt.subplot(1, 2, 1)
plt.plot(train_accuracies, label='Train Accuracy')
plt.plot(val_accuracies, label='Validation Accuracy')
plt.title('Model Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy (%)')
plt.legend()

# Loss Subplot
plt.subplot(1, 2, 2)
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Validation Loss')
plt.title('Model Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()